services:
  mariadb:
    container_name: mariadb
    networks: 
      - n_inception
    secrets:
      - DBPASS
    build: requirements/mariadb
    image: mariadb
    environment:
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
    volumes:
      - maria_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DBUSER}"]
      interval: 10s
      retries: 3
      timeout: 10s

  php-fpm:
    secrets:
      - DBPASS
      - WP_PASS_AD
      - WP_PASS_USER
    container_name: php-fpm
    image: php-fpm
    volumes: 
      - data:/WordPress
    build: requirements/wordpress
    ports:
      - 9000:9000
    networks:
      - n_inception
    environment:
      - WPUSER_ADMIN=${WPUSER_ADMIN}
      - WPEMAIL_ADMIN=${WPEMAIL_ADMIN}
      - WPTITLE=${WPTITLE}
      - WPURL=${WPURL}
      - WPUSER=${WPUSER}
      - WPEMAIL=${WPEMAIL}
      - WPROLE=${WPROLE}
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBHOST=${DBHOST}
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "cgi-fcgi", "-bind", "-connect", "localhost:9000"]
      interval: 10s
      retries: 3
      timeout: 30s
  nginx:
    container_name: nginx
    networks: 
      - n_inception
    volumes:
      - data:/WordPress
    build: requirements/nginx
    image: nginx
    ports: 
      - 443:443
    environment:
      - FPM_PHPHOST=${FPM_PHPHOST}
    depends_on:
          php-fpm:
            condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-k",  "https://localhost:443"]
      interval: 10s
      retries: 3
      timeout: 10s
secrets:
  DBPASS:
    file: ../secrets/DBPASS.env
  WP_PASS_AD:
    file: ../secrets/WP_PASS_AD.env
  WP_PASS_USER:
    file: ../secrets/WP_PASS_USER.env
volumes:
  data:
    name: data
  maria_db_data:
    name: maria_db_data
networks :
  n_inception:
    name: n_inception

