services:
  mariadb:
    container_name: mariadb
    networks: 
      - n_inception
    secrets:
      - DBPASS
    build: requirements/mariadb
    image: mariadb
    environment:
      - DBNAME
      - DBUSER
    volumes:
      - maria_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      interval: 10s
      retries: 3
      timeout: 10s



  wordpress:
    secrets:
      - DBPASS
      - WP_PASS_AD
      - WP_PASS_USER
    container_name: wordpress
    image: wordpress
    volumes: 
      - data:/WordPress
    build: requirements/wordpress
    ports:
      - 9000:9000
    networks:
      - n_inception
    environment:
      - WPUSER_ADMIN
      - WPEMAIL_ADMIN
      - WPTITLE
      - WPURL
      - WPUSER
      - WPEMAIL
      - WPROLE
      - DBNAME
      - DBUSER
      - DBHOST
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "cgi-fcgi", "-bind", "-connect", "localhost:9000"]
      interval: 10s
      retries: 3
      timeout: 30s
  nginx:
    container_name: nginx
    networks: 
      - n_inception
    restart: on-failure:3
    volumes:
      - data:/WordPress
    build: requirements/nginx
    image: nginx
    ports: 
      - 443:443
    environment:
      - FPM_PHPHOST
    depends_on:
          wordpress:
            condition: service_healthy





secrets:
  DBPASS:
    file: ../secrets/DBPASS.env
  WP_PASS_AD:
    file: ../secrets/WP_PASS_AD.env
  WP_PASS_USER:
    file: ../secrets/WP_PASS_USER.env



volumes:
  data:
    name: data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/achamdao/data/Wordpress_files
  maria_db_data:
    name: maria_db_data
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: /home/achamdao/data/Wordpress_database


networks :
  n_inception:
    name: n_inception

